eqfeed_callback({
    "type":"FeatureCollection",
    "features":[
        {
            "type":"Feature",
            "properties":{
                "quantity":1,
                "place":"Alemanha"
            },
            "geometry":{
                "type":"Point",
                "coordinates":[-44.276962,-2.5341152]
            }
        },
        {
            "type":"Feature",
            "properties":{
                "quantity":1,
                "place":"Anjo da Guarda"
            },
            "geometry":{
                "type":"Point",
                "coordinates":[-44.3317914,-2.5511945]
            }
        },
        {
            "type":"Feature",
            "properties":{
                "quantity":1,
                "place":"Aurora"
            },
            "geometry":{
                "type":"Point",
                "coordinates":[-44.2382656,-2.5479703]
            }
        },
        {
            "type":"Feature",
            "properties":{
                "quantity":3,
                "place":"Bairro de Fátima"
            },
            "geometry":{
                "type":"Point",
                "coordinates":[-44.2845419,-2.5475454]
            }
        },
        {
            "type":"Feature",
            "properties":{
                "quantity":1,
                "place":"Bela Vista / Primavera I (Cohajap)"
            },
            "geometry":{
                "type":"Point",
                "coordinates":[-44.2451078,-2.4979515]
            }
        },
        {
            "type":"Feature",
            "properties":{
                "quantity":1,
                "place":"Bequimão"
            },
            "geometry":{
                "type":"Point",
                "coordinates":[-44.2628238,-2.5263746]
            }
        },
        {
            "type":"Feature",
            "properties":{
                "quantity":1,
                "place":"Bom Jesus"
            },
            "geometry":{
                "type":"Point",
                "coordinates":[-44.2753217,-2.5650939]
            }
        },
        {
            "type":"Feature",
            "properties":{
                "quantity":8,
                "place":"Calhau"
            },
            "geometry":{
                "type":"Point",
                "coordinates":[-44.2747715,-2.4900894]
            }
        },
        {
            "type":"Feature",
            "properties":{
                "quantity":1,
                "place":"Camboa"
            },
            "geometry":{
                "type":"Point",
                "coordinates":[-44.2942225,-2.5285903]
            }
        },
        {
            "type":"Feature",
            "properties":{
                "quantity":1,
                "place":"Caratatiua"
            },
            "geometry":{
                "type":"Point",
                "coordinates":[-44.2703407,-2.5417533]
            }
        },
        {
            "type":"Feature",
            "properties":{
                "quantity":5,
                "place":"Centro"
            },
            "geometry":{
                "type":"Point",
                "coordinates":[-44.3034532,-2.5298477]
            }
        },
        {
            "type":"Feature",
            "properties":{
                "quantity":2,
                "place":"Chácara Brasil"
            },
            "geometry":{
                "type":"Point",
                "coordinates":[-44.2208134,-2.5042804]
            }
        },
        {
            "type":"Feature",
            "properties":{
                "quantity":2,
                "place":"Cidade Operária"
            },
            "geometry":{
                "type":"Point",
                "coordinates":[-44.2087954,-2.5893822]
            }
        },
        {
            "type":"Feature",
            "properties":{
                "quantity":2,
                "place":"Cohafuma"
            },
            "geometry":{
                "type":"Point",
                "coordinates":[-44.2822194,-2.5068896]
            }
        },
        {
            "type":"Feature",
            "properties":{
                "quantity":3,
                "place":"Cohama"
            },
            "geometry":{
                "type":"Point",
                "coordinates":[-44.2442776,-2.5152495]
            }
        },
        {
            "type":"Feature",
            "properties":{
                "quantity":2,
                "place":"Cohatrac I, II, III, IV, Primavera-Cohatrac"
            },
            "geometry":{
                "type":"Point",
                "coordinates":[-44.2204112,-2.537547]
            }
        },
        {
            "type":"Feature",
            "properties":{
                "quantity":1,
                "place":"Conjunto Dom Sebastião / Vila dos Nobres / Pq. Dos Nobres / Parque Timbira"
            },
            "geometry":{
                "type":"Point",
                "coordinates":[-44.2772461,-2.559986]
            }
        },
        {
            "type":"Feature",
            "properties":{
                "quantity":4,
                "place":"Conjunto Habitacional Vinhais"
            },
            "geometry":{
                "type":"Point",
                "coordinates":[-44.2575265,-2.5154282]
            }
        },
        {
            "type":"Feature",
            "properties":{
                "quantity":1,
                "place":"Coroadinho"
            },
            "geometry":{
                "type":"Point",
                "coordinates":[-44.2785507,-2.5670857]
            }
        },
        {
            "type":"Feature",
            "properties":{
                "quantity":1,
                "place":"Cruzeiro do Anil"
            },
            "geometry":{
                "type":"Point",
                "coordinates":[-44.2349991,-2.5407558]
            }
        },
        {
            "type":"Feature",
            "properties":{
                "quantity":1,
                "place":"Forquilha"
            },
            "geometry":{
                "type":"Point",
                "coordinates":[1,111.16,26.3832,5.977]
            }
        },
        {
            "type":"Feature",
            "properties":{
                "quantity":1,
                "place":"Jaracaty"
            },
            "geometry":{
                "type":"Point",
                "coordinates":[-44.2212368,-2.5619517]
            }
        },
        {
            "type":"Feature",
            "properties":{
                "quantity":1,
                "place":"Jardim América"
            },
            "geometry":{
                "type":"Point",
                "coordinates":[-44.2011068,-2.5855645]
            }
        },
        {
            "type":"Feature",
            "properties":{
                "quantity":2,
                "place":"Jardim das Margaridas / Parque Aurora / Planalto Anil I, II, III"
            },
            "geometry":{
                "type":"Point",
                "coordinates":[-44.2131834,-2.5466773]
            }
        },
        {
            "type":"Feature",
            "properties":{
                "quantity":1,
                "place":"Jordoa"
            },
            "geometry":{
                "type":"Point",
                "coordinates":[-44.2643478,-2.5488164]
            }
        },
        {
            "type":"Feature",
            "properties":{
                "quantity":1,
                "place":"Liberdade"
            },
            "geometry":{
                "type":"Point",
                "coordinates":[-44.2905726,-2.5215589]
            }
        },
        {
            "type":"Feature",
            "properties":{
                "quantity":1,
                "place":"Maranhão Novo"
            },
            "geometry":{
                "type":"Point",
                "coordinates":[-44.2577306,-2.5286523]
            }
        },
        {
            "type":"Feature",
            "properties":{
                "quantity":2,
                "place":"Monte Castelo"
            },
            "geometry":{
                "type":"Point",
                "coordinates":[-44.2858981,-2.5358477]
            }
        },
        {
            "type":"Feature",
            "properties":{
                "quantity":3,
                "place":"Olho D’água"
            },
            "geometry":{
                "type":"Point",
                "coordinates":[-44.2363982,-2.487794]
            }
        },
        {
            "type":"Feature",
            "properties":{
                "quantity":1,
                "place":"Pindorama"
            },
            "geometry":{
                "type":"Point",
                "coordinates":[-44.3007359,-2.557369]
            }
        },
        {
            "type":"Feature",
            "properties":{
                "quantity":2,
                "place":"Planalto Vinhais II"
            },
            "geometry":{
                "type":"Point",
                "coordinates":[-44.2606969,-2.5042998]
            }
        },
        {
            "type":"Feature",
            "properties":{
                "quantity":8,
                "place":"Ponta d’Areia"
            },
            "geometry":{
                "type":"Point",
                "coordinates":[-44.313728,-2.4969516]
            }
        },
        {
            "type":"Feature",
            "properties":{
                "quantity":2,
                "place":"Ponta do Farol"
            },
            "geometry":{
                "type":"Point",
                "coordinates":[-44.3015839,-2.4916594]
            }
        },
        {
            "type":"Feature",
            "properties":{
                "quantity":1,
                "place":"Quitandinha / Vinhais I / Vinhais II"
            },
            "geometry":{
                "type":"Point",
                "coordinates":[-44.2607293,-2.5077705]
            }
        },
        {
            "type":"Feature",
            "properties":{
                "quantity":14,
                "place":"Renascença"
            },
            "geometry":{
                "type":"Point",
                "coordinates":[-44.2974207,-2.499955]
            }
        },
        {
            "type":"Feature",
            "properties":{
                "quantity":1,
                "place":"Retiro Natal"
            },
            "geometry":{
                "type":"Point",
                "coordinates":[-44.2343924,-2.5708807]
            }
        },
        {
            "type":"Feature",
            "properties":{
                "quantity":1,
                "place":"Sacavém"
            },
            "geometry":{
                "type":"Point",
                "coordinates":[-44.2616007,-2.5543175]
            }
        },
        {
            "type":"Feature",
            "properties":{
                "quantity":1,
                "place":"Santo Antonio"
            },
            "geometry":{
                "type":"Point",
                "coordinates":[-44.2966286,-2.6418267]
            }
        },
        {
            "type":"Feature",
            "properties":{
                "quantity":2,
                "place":"São Francisco"
            },
            "geometry":{
                "type":"Point",
                "coordinates":[-44.3063263,-2.5095515]
            }
        },
        {
            "type":"Feature",
            "properties":{
                "quantity":1,
                "place":"São Marcos"
            },
            "geometry":{
                "type":"Point",
                "coordinates":[-44.3053001,-2.4927561]
            }
        },
        {
            "type":"Feature",
            "properties":{
                "quantity":1,
                "place":"Sá Viana"
            },
            "geometry":{
                "type":"Point",
                "coordinates":[-44.3087299,-2.5595196]
            }
        },
        {
            "type":"Feature",
            "properties":{
                "quantity":9,
                "place":"Turu"
            },
            "geometry":{
                "type":"Point",
                "coordinates":[-44.2190253,-2.5109528]
            }
        },
        {
            "type":"Feature",
            "properties":{
                "quantity":1,
                "place":"Vila Embratel"
            },
            "geometry":{
                "type":"Point",
                "coordinates":[-44.3122425,-2.5725159]
            }
        }
    ]
});